// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CitiesLookup
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("search")]
        public string Search { get; set; }

        [JsonProperty("foundCities")]
        public FoundCity[] FoundCities { get; set; }
    }

    public partial class FoundCity
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("altName")]
        public string AltName { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("countryName")]
        public string CountryName { get; set; }

        [JsonProperty("featureCode")]
        public string FeatureCode { get; set; }

        [JsonProperty("population")]
        public long? Population { get; set; }

        [JsonProperty("populationCategory")]
        public string PopulationCategory { get; set; }

        [JsonProperty("loc")]
        public Loc Loc { get; set; }
    }

    public partial class Loc
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("coordinates")]
        public double?[] Coordinates { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
