// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CitiesLookup
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("search")]
        public string Search { get; set; }

        [JsonProperty("foundCities")]
        public FoundCity[] FoundCities { get; set; }
    }

    public partial class FoundCity
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("altName")]
        public string AltName { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("featureCode")]
        public FeatureCode FeatureCode { get; set; }

        [JsonProperty("population")]
        public long Population { get; set; }

        [JsonProperty("loc")]
        public Loc Loc { get; set; }
    }

    public partial class Loc
    {
        [JsonProperty("type")]
        public TypeEnum Type { get; set; }

        [JsonProperty("coordinates")]
        public double[] Coordinates { get; set; }
    }

    public enum FeatureCode { Ppl, Ppla, Ppla2, Pplx };

    public enum TypeEnum { Point };
}
